name: GitHub Signed Commit
description: GitHub Action to create signed commits

branding:
  icon: git-commit
  color: orange

inputs:
  files:
    description: |
      Multi-line string of file paths to be committed, relative to the current workspace.
    required: true
  workspace:
    description: |
      Directory containing files to be committed. Default: GitHub workspace directory (root of repository).
    required: false
    default: ''
  commit-message:
    description: |
      Commit message for the file changes.
    required: true
  branch-name:
    description: |
      Branch to commit to. Default: Workflow triggered branch.
    required: false
    default: ''
  branch-push-force:
    description: |
      --force flag when running git push <branch-name>.
    required: false
    default: false
  tag:
    description: |
      Tag for the commit.
    required: false
    default: ''

outputs:
  commit-sha:
    description: SHA of created commit

runs:
  using: node20
  main: dist/index.js
